language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
addons:
  postgresql: "9.3"
env:
  - DATABASE_URL=postgresql://postgres@localhost/explore_api_test
before_script:
  - psql -c 'create database explore_api_test;' -U postgres
