# Explore app settings
production:
  audio_server_url: <%= ENV['AUDIO_SERVER_URL'] %>
  aws_access_key: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  cache_bucket: <%= ENV['CACHE_BUCKET'] %>
  backend_api_key: <%= ENV['BACKEND_API_KEY'] %>

development:
  audio_server_url: http://localhost:5000
  aws_access_key: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  cache_bucket: <%= ENV['CACHE_BUCKET'] %>
  aws_region:
  backend_api_key: exploreapollo
